[project]
name = "django-blueprint"
version = "1.0.0-rc.2"
description = "Common models and fields for adding CMS-like functionality to Django."
authors = [
    {name = "Leon van der Grient",email = "leon@dwarsbit.nl"}
]
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jsonschema (>=4.26.0,<5.0.0)",
    "nh3 (>=0.3.0,<1.0.0)"
]

[tool.poetry]
packages = [{include = "blueprint"}]

[tool.poetry.group.dev.dependencies]
black = "^26.1.0"
Django= "^6.0.2"
pytest = "^8.4.0"
pytest-django = "^4.11.0"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings"
testpaths = ["tests"]
python_files = ["test_*.py"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
