# Generated by Django 6.0.2 on 2026-10-05 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbp_media_library", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="alt_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Describes a picture for screen readers",
                max_length=255,
                verbose_name="Alt text",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="dbp_media_library.folder",
                verbose_name="Folder",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="size",
            field=models.PositiveBigIntegerField(
                editable=False, null=True, verbose_name="File size"
            ),
        ),
    ]
